version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: itda
      POSTGRES_PASSWORD: itda
      POSTGRES_DB: itda
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U itda"]
      interval: 3s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bash -c "uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload" 
    working_dir: /app
    ports:
      - "8008:8000"
    env_file: .env
    volumes:
      - ./backend:/app/backend

    depends_on:
      db:
        condition: service_healthy
    environment:
        WATCHFILES_FORCE_POLLING: "true"
        WATCHFILES_POLL_INTERVAL: "0.2" 
volumes:
  postgres_data: {} 